### ISSUE TITLE
Error flattening models using R410A refrigerant in OMEdit 1.12.0

### ISSUE THREAD

**Issue by elcoo** [ibpsa/modelica-ibpsa#1044]
Flattening models using the R410A refrigerant is leading to compile errors. Compiling the R410A_dSpecificVolumeVap_pT Validation file for example returns this error:
```
[1] 11:17:11 Übersetzung Fehler
[IBPSA.Media.Refrigerants.R410A.specificVolumeVap_pT: 40:3-40:35]: Variable A not found in scope IBPSA.Media.Refrigerants.R410A.specificVolumeVap_pT.

[2] 11:17:11 Übersetzung Fehler
[IBPSA.Media.Refrigerants.R410A.dSpecificVolumeVap_pT: 32:3-32:65]: Class IBPSA.Media.Refrigerants.R410A.specificVolumeVap_pT not found in scope IBPSA.Media.Refrigerants.R410A.dSpecificVolumeVap_pT (looking for a function or record).
```
Trying to compile the "ScrollWaterToWater_OneRoomRadiator" Heatpump-Example leads to this error:

```
[4] 11:19:35 Übersetzung Fehler
[IBPSA.Media.Refrigerants.R410A.specificIsobaricHeatCapacityVap_Tv: 42:3-42:35]: Variable A not found in scope IBPSA.Media.Refrigerants.R410A.specificIsobaricHeatCapacityVap_Tv.

[5] 11:19:35 Übersetzung Fehler
[IBPSA.Media.Refrigerants.R410A.isentropicExponentVap_Tv: 20:3-20:80]: Class IBPSA.Media.Refrigerants.R410A.specificIsobaricHeatCapacityVap_Tv not found in scope IBPSA.Fluid.HeatPumps.Compressors.ScrollCompressor$heaPum$com.ref.isentropicExponentVap_Tv (looking for a function or record).
```

Other examples seem to compile fine, although I didn't try them all. I can't figure out why "Variable A" could not be found, as it seems to be declared correctly in the function files.

**Comment by thorade** [comment]
This model does not simulate in the current OpenModelica master:
https://libraries.openmodelica.org/branches/master/IBPSA_latest/IBPSA_latest.html

OpenModelica guys are working on a new frontend, results are here:
https://libraries.openmodelica.org/branches/newInst/IBPSA_latest/IBPSA_latest.html

In general, it will take some more months from now until the new frontend is on par or better than the old frontend, but for this specific model, the new frontend is already better!

So, I asked you to open this issue here, but now I think it can be closed as wont't fix and instead you'll have to wait for the new frontend.

**Comment by mwetter** [comment]
Closed as this is handled with other OpenModelica testing.
