### ISSUE TITLE
Temperature States in Plug Flow Pipe

### ISSUE THREAD

**Issue by MichaMans** [ibpsa/modelica-ibpsa#1092]
Hi everyone,

for an easier usage of the PlugFlowPipe Model, I would suggest to implement the show_T boolean for state calculations at the ports.

For more detail:

**What is the problem?**

At the moment there is no direct implementation of showing the temperature states of the PlugFlowPipe Model ports. This feature would be a handy addition to improve the usability of the model

**How do we want to solve it? Describe the solution you'd like**

As far as i'm aware, there should be two possible solutions:

Option 1: 
- Implementation in direct in the PlugFlowPipe model with the integration of the boolean show_T and the corresponding state calculations for the ports

Option 2:
- Implementation in the PartialTwoPortVector Model to enable the usage directly from the BaseClass

**Describe alternatives you've considered**

As far as i know there are now alternatives available in this pipe model

**Additional context**

@bramvdh91 @FelixBue @mwetter were would you like to see the implementation (if there are no general objections on that enhancement)

**Comment by bramvdh91** [comment]
@MichaMans I think this would be a real valuable addition to the model, since it would make temperatures more accessible in a place where you expect them instead of needing to do all administration with separate temperature sensors. 
For me option 1 sounds more logical; in the vectorized port you just have a repetition of the temperature of the mixing volume if I'm not mistaken.
