### ISSUE TITLE
initialising Borefield to custom state

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#1127]
@MassimoCimmino @damienpicard I'd like to do a ~20 year Borefield simulation with a known thermal power profile and use the resulting Borefield state in a _new_ simulation. Is it possible to export the Borefield 'state' to file and load it as an initial condition for a new simulation?

**Comment by damienpicard** [comment]
@Mathadon it should be possible by saving the values of the `IDEAS.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.GroundTemperatureResponse` model and using them to initialize the borefield model. @MassimoCimmino and @AlexLaferriere can you confirm and shortly describe how to do it as you have implemented that model? It would be very useful :)

**Comment by MassimoCimmino** [comment]
@Mathadon :

@damienpicard is correct. The ground response (long-term response) is handled in `IBPSA.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.GroundTemperatureResponse`. The state for this model is given by the variable `QAgg_flow` and the time since start of bore field operation `t_start`. The borehole states are given by the value of the capacitance and fluid nodes in `IBPSA.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.OneUTube`.

We had at one point a procedure to initialize `QAgg_flow` based on a text file of historical ground loads. You would provide a 2-column table of time and heat transfer rate to the soil and the state would be estimated at initialization. I could look into this if this process fits with your plans.

**Comment by mwetter** [comment]
@Mathadon : Can't you get and set the state through the FMI API?

**Comment by Mathadon** [comment]
@MassimoCimmino In the interest of time I am looking into a different solution where I would not need this functionality. I'll close this for now assuming that it will work. Thanks anyway!
