### ISSUE TITLE
Enhance ROM (ThermalZone.RC) for co2 balance

### ISSUE THREAD

**Issue by katharinabr** [ibpsa/modelica-ibpsa#1275]
**What do I want to do?**
I want to implement the possibility to take into account co2 production and co2 balance in thermal zones.
For this reason I would like to modify the air volume model in the ThermalZones.ReduceOrder.RC.OneElement.mo.

**How I want to solve it**

I will rename the boolean parameter use_moisture_balance into use_moisture_co2_balance (or implement a new boolean parameter use_co2_balance that will be false per default). This depends wether it should be possible to use moisture and co2 independent from each other.
In the AixLib we will use moisture and co2 balance together to avoid too many models due to every possible combination of used balances.

An additional input connector co2_flow conditioned with use_moisture_co2_balance will be implemented and conditionally connected to the volMoistAir.

In the Aixlib this implementation has been performed. To avoid merge-conflicts with the IBPSA, I would like to implement the same changes into the IBPSA. Changes can be seen in issue 797 of the Aixlib.

Are there any concerns about this changes?

**Comment by mwetter** [comment]
@katharinabr 
Moisture and CO2 can be used independently, and I think best is to use `C` and then it is up to the user what kind of trace substances are modeled. 

Please use
```modelica
  parameter Boolean use_C_flow = false
    "Set to true to enable input connector for trace substance"
    annotation(Evaluate=true, Dialog(tab="Advanced"));

  Modelica.Blocks.Interfaces.RealInput[Medium.nC] C_flow if use_C_flow
    "Trace substance mass flow rate added to the thermal zone"
    annotation (Placement(transformation(extent={{-140,-80},{-100,-40}})));
```
so that we have the same model pattern as is already used in `MixingVolumeMoistAir`.

**Comment by katharinabr** [comment]
@mwetter Ok, could you create a branch, please?

**Comment by mwetter** [comment]
@katharinabr : I created the branch `issue1275_romTraceSubstances`. Sorry for the delay, I must have missed this during travel.

**Comment by mwetter** [comment]
@katharinabr Thanks for the PR, which I merged into `issue1275_romTraceSubstances` and further edited as `if-then` are not needed because Modelica ensure that `connect` statements are removed if the connectors are removed.

Can you please also add an example that illustrates and, more importantly, tests the use of the configuration with `use_C_flow=true`. This is needed for the CI test so we keep testing and make sure it is implemented correctly and won't break in the future.

**Comment by mwetter** [comment]
@katharinabr : I merged your PR and further edited the models. I did mainly the following:
- Changed the test to one week only so we actually see how the concentration changes
- Changed the emission to have a periodicity of 1 day rather than 1 hour, again so we see how CO2 is built up.

Can you please address the following after merging the recent changes in your branch:
- [ ] Change the tests to have some ventilation. Currently, there is no ventilation and hence CO2 is just linearly increasing or decreasing. Please add an emission rate and a ventilation rate that is typical for such a room size, and then add to the CI tests how much PPM there is.
- [ ] I believe you copied other examples and added the CO2 emission. Please simply extend these other examples, there is no need to copy all the models.
- [ ] Update the info section of the new test models to describe what they are doing and testing. Now they are just copies of the original example. Please explain to the user what this model tests.
- [ ] Update the release notes of the new test models.

**Comment by mwetter** [comment]
@katharinabr : Thanks for the PR. I revised the model slightly, mainly changing the outdoor CO2 concentration to more realistic values and using a shorter ramp so that CO2 stabilizes in the last days of the test time interval.
