### ISSUE TITLE
Changing the location of inlet and outlet of the Enhanced Stratified tank

### ISSUE THREAD

**Issue by amirj1984** [ibpsa/modelica-ibpsa#1307]
**What is the objective?**
The location of inlet and outlet of the built-in Simple and Enhanced Stratified tank models are in segments 1 and nSeg, which can be reveresed. The change in the locations of inlet and outlet (e.g. segments 2 and 25 for a tank with nSeg=30) can be done easily for the Simple Stratified tank; however, this is not the case for the Enhanced Stratified one as it includes other two components ("str" and "H_vol_flow") which link the ports and mixing volume.

**Comment by Mathadon** [comment]
If I understand correctly, the problem is that `IBPSA.Fluid.Storage.Stratified` has a vector input `fluPorVol`, which allows custom volume connections, while `IBPSA.Fluid.Storage.StratifiedEnhanced` does not. This is quite likely because the QUICK discretization scheme is not implemented generically enough to allow for the additional port connections. @mwetter is this something that could be added or is it too complex?

**Comment by mwetter** [comment]
I would think it takes at least a week or two for a skilled modeler to make the changes, document and test them extensively for different port configurations. I recall that the model that enhances the stratification was quite sensitive to numerical overshoot that then violated the 2nd law. Wangda and I spent considerable time to make sure it is robust. See also the model limitations in the info section as this would like require a high number of volumes to satisfy.

**Comment by Mathadon** [comment]
Looks like something that we currently don't have the time for then. @amirj1984 can this issue be closed?

**Comment by amirj1984** [comment]
@Mathadon @mwetter Thank you very much for your advice.
