### ISSUE TITLE
WetCoilCounterFlow with condensate removal

### ISSUE THREAD

**Issue by justnielsen** [ibpsa/modelica-ibpsa#1355]
I'm using `Fluid.HeatExchangers.WetCoilCounterFlow` as a flue gas condenser for a district heating boiler, similar to the example `Fluid.HeatExchangers.Examples.WetCoilCounterFlowMassFlow`. 

However, due to the following restrictions I am not allowed to modify the constant `simplify_mWat_flow` when I instantiate `WetCoilCounterFlow`.

1. in `Fluid.HeatExchangers.BaseClasses.HexElementLatent` the redeclaration of `vol2` is `final`.
2. in `Fluid.HeatExchangers.DryCoilCounterFlow` the replaceable model `ele` is `protected` (which just gives me a warning)

My reason for modifying `simplify_mWat_flow` is to simulate the removal of condensate  from the moist air stream, to se that `port_b2.m_flow` < `port_a2.m_flow`.

## Reproduction of problem

- In `Fluid.HeatExchangers.Examples.WetCoilCounterFlowMassFlow` insert the modifier `ele(each vol2(simplify_mWat_flow=false))` in the instantiation of `hex` (line 11).
- Simulation/Check gives error

## Fixing of problem
- in `Fluid.HeatExchangers.BaseClasses.HexElementLatent` remove `final` from the line `redeclare  Buildings.Fluid.MixingVolumes.BaseClasses.MixingVolumeHeatMoisturePort vol2(` (line 8)
-  in `Fluid.HeatExchangers.DryCoilCounterFlow` make `ele` public (line 119)

**Comment by mwetter** [comment]
@justnielsen : Can you please open this ticket in the Buildings library and close this one as the model is only present in the Buildings library.
Some initial comment: I would rather keep `ele` protected as making it public will significantly increase the output with data that most users won't be interested in. We could however see if we can expose `simplify_mWat_flow` as a constant so you can change it in your model. However, you need to make sure the model is applicable if `mWat_flow` is large because it implements
```
ports_H_flow[i]     = semiLinear(ports[i].m_flow, inStream(ports[i].h_outflow), ports[i].h_outflow)
```
which is not applicable for this case. Maybe for your steam condensing coil, a different base class would be better suited.

**Comment by justnielsen** [comment]
@mwetter : sure, I've moved it to issue [#1920](https://github.com/lbl-srg/modelica-buildings/issues/1920)
I'm not quite sure that I understand the details in your last concern, so I added some more details to my description in issue [#1920](https://github.com/lbl-srg/modelica-buildings/issues/1920)

Thanks
