### ISSUE TITLE
Reverse flow in Check Valve Model

### ISSUE THREAD

**Issue by khinkelman** [ibpsa/modelica-ibpsa#1378]
The [IBPSA.Fluid.FixedResistances.CheckValve](https://github.com/ibpsa/modelica-ibpsa/blob/master/IBPSA/Fluid/FixedResistances/CheckValve.mo) model permits reverse flow, which should not be allowed. Please see the simple test example below. 

![image](https://user-images.githubusercontent.com/44682485/87866084-3f916200-c93a-11ea-975b-2448acf7e1d1.png)

![image](https://user-images.githubusercontent.com/44682485/87866091-63ed3e80-c93a-11ea-85d8-227d5063a76c.png)

**Comment by Mathadon** [comment]
@khinkelman this is a user error. You are telling Modelica: 'no matter what, force a sinusoidal flow rate through the check valve'. Modelica takes the flow rate that you request as an input and computes the pressure drop over the check valve from that input. If you check the pressure drop then you will see that it is gigantic, probably so large that the pipe with burst if it were a real check valve. To put it otherwise, what you are modeling is non-physical. There is no such thing as an ideal pump that can push whatever flow rate through a closed check valve, use a `PrescribedFlow_dp` pump instead.

**Comment by khinkelman** [comment]
Thanks @Mathadon, I see what you are saying. Thank you very much for the explanation and suggestions.
