### ISSUE TITLE
Compatibility with MSL 4.0

### ISSUE THREAD

**Issue by justnielsen** [ibpsa/modelica-ibpsa#1423]
I recently installed Dymola 2021x which by default uses _Modelica Standard Library version 4.0.0_. 

I'm using _Modelica Buildings Library_ as a Git submodule — usually pointing to the latest commit to benefit from the frequent updates. However, this doesn't seem to work with MSL 4.0.0 _without_ conversion from MSL 3.2.3 which changes a lot of files in the local copy of MBL (e.g. `Modelica.SIunits` → `Modelica.Units.SI`).

What are the plans for upgrading MBL to MSL 4.0.0 on Git? And is there a better way for me than running the conversion script everytime I point to a newer commit of MBL?

**Comment by mwetter** [comment]
Does Dymola 2021x provide instructions for how to install (or select) Modelica 3.2.3? The IBPSA and Buildings libraries use the annotation that should load the Modelica Standard Library 3.2.3 if it is available on your installation. I would hope Dymola provides this backward compatibility.

We don't anticipate updating IBPSA and Buildings to MSL 4.0.0 before OCT and OpenModelica also ship MSL 4.0.0. You should however be able to run Dymola's conversion script to update IBPSA or Buildings to MSL 4.0.0 if you want to use MSL 4.0.0 rather than using MSL 3.2.3. This worked with the latest Dymola 2021x beta.

**Comment by justnielsen** [comment]
Yes, the Dymola release notes describe how to install MSL 3.2.3 from a zip archive included in the installation (I couldn't find the file, though). However, since I've upgraded all my own libraries (many of which I use together with MBL) to MSL 4.0.0 I'm not interested in using MSL 3.2.3.

The conversion script to MSL 4.0.0 works fine so I'll just run it after I've pull the latest Buildings Library from Github.

**Comment by marcusfuchs** [comment]
Just to add another perspective to the discussion:

For our team, MSL 3.2.3 was included in the `extra/` directory within the download of Dymola 2021x. After selecting MSL version 3.2.3 in the `Tools > Options > Version` as described in the release notes everything works for us. Copying MSL 3.2.3 from an older Dymola version also worked just as well. For us staying on MSL 3.2.3 for a bit longer is working out, even though we would welcome upgrading when the Modelica IBPSA Library is ready for this.

**Comment by justnielsen** [comment]
I downloaded the Dymola installer as an `.exe` file from our Scandiavian reseller [scanscot.com](https://www.scanscot.com). I guess the `extra/` directory must be located in another type of installation file (`.zip`?). It is not located anywhere in the installation directory as far as I can see.

**Comment by marcusfuchs** [comment]
Yes, we download a zip (`Dymola_2021x.AM_CAT_Dymola.Windows64.1-1.zip` in this case) from https://software.3ds.com which includes the `setup.exe` as well as the `extra/` directory.

**Comment by thorade** [comment]
I installed from zip and can switch to 3.2.3 in the options menu, but Dymola is still opening MSL 4, and the conversion popup is coming. Anyone else is experiencing this? I used a .mos script to open my libraries.

![image](https://user-images.githubusercontent.com/314571/101018539-f3069600-356b-11eb-8cd4-97df6985af68.png)

**Comment by marcusfuchs** [comment]
@thorade Yes, we saw the same behavior initially. In our case this was because Dymola did not ship MSL 3.2.3 by default. After copying MSL 3.2.3 into a folder `...\Dymola 2021x\Modelica\Library\Modelica 3.2.3` things worked fine. We tried the MSL from the zip's `extra/` folder as well as the `Modelica 3.2.3` folder from an older version of Dymola and both worked. I suppose you could also use 3.2.3 from MSL's GitHub as long as you copy it to this destination.

**Comment by justnielsen** [comment]
@marcusfuchs I downloaded MSL 3.2.3 from GitHub ([https://github.com/modelica/ModelicaStandardLibrary/releases/download/v3.2.3%2Bbuild.4/ModelicaStandardLibrary_v3.2.3.zip](https://github.com/modelica/ModelicaStandardLibrary/releases/download/v3.2.3%2Bbuild.4/ModelicaStandardLibrary_v3.2.3.zip)). It works just fine when I select version 3.2.3 in Dymola and **restart** Dymola. "Refreshing" MSL from the context menu is not enough to reload a different version of MSL — probably because it is located in another directory.

**Comment by thorade** [comment]
@marcusfuchs Does it work for you from a mos script? 
If I open Dymola, then open Modelica, it shows MSL 3.2.3, but if I open my libraries from a mos script, it will still open MSL 4. My current workaround is to open Dymola, then open MSL (just double click in the package browser), then go to Simulation, open and run script. But that is of course a bit annoying.

**Comment by marcusfuchs** [comment]
@thorade I am currently hardly using any custom mos scripts except for the ones to run BuildingsPy regression tests. But when I do a test run of e.g. https://github.com/ibpsa/modelica-ibpsa/blob/master/IBPSA/Resources/Scripts/Dymola/Airflow/Multizone/Examples/ChimneyShaftNoVolume.mos Dymola does open 3.2.3  as specified by the `uses` statement in IBPSA.

**Comment by mwetter** [comment]
I believe this can be closed. If anything needs to be fixed, please make a pull request and reopen it.
