### ISSUE TITLE
Unit inconsistency in SolarGain

### ISSUE THREAD

**Issue by hannah-kruetzfeldt** [ibpsa/modelica-ibpsa#1644]
In IBPSA.ThermalZones.ReducedOrder.SolarGain.CorrectionGDoublePane there is a unit inconsistency with sub-expression "corGDouPan.Ta2_diff" has unit "1" and sub-expression "corGDouPan.Qsek2_diff" has unit "W/(m2.K)".

This is due to a non physical formula in VDI 6007-3, which the model is based on. 

Parameters Q21_diff and Q22_diff are auxiliary parameters that should be dimensionless.
To resolve this issue I suggest introducing an auxiliary parameter with value 1 [W/m²K] and use it to make UWin dimensionless. This way it is more obvious that it is not a physical equation.

**Comment by FWuellhorst** [comment]
@mwetter : 
@hannah-kruetzfeldt would like to provide her solution via a PR. Could you add her to the ibpsa-group? Or should we open a PR via a fork?

**Comment by mwetter** [comment]
@hannah-kruetzfeldt : you should have an invitation to join the group.
I haven't looked at it in detail, but one could also avoid specifying the unit (rather than setting it to `1`) in which case there should not be any warning about mismatching units. As these seem to be all protected variables and parameters, removing the unit specification on these non-physical intermediate quantities seems fine.

**Comment by hannah-kruetzfeldt** [comment]
@mwetter: Thank you.
One parameter that is included in the equation is Uwin from the baseClass, which in my opinion should keep its unit as it's not protected and just the overall U-value of the window.
