### ISSUE TITLE
Movers.Preconfigured.SpeedControlled_y has circular parameter binding

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1705]
The model `Movers.Preconfigured.SpeedControlled_y` has as a default value
`m_flow_nominal = max(per.pressure.V_flow)*rho_default`,
and then it sets
```modelica
...
  extends Buildings.Fluid.Movers.SpeedControlled_y(
    final per(
            pressure(
              V_flow=m_flow_nominal/rho_default*{0, 1, 2},
              dp=if rho_default < 500
                   then dp_nominal*{1.12, 1, 0}
                   else dp_nominal*{1.14, 1, 0.42}),
            powerOrEfficiencyIsHydraulic=true,
```
This is circular and there should be no default value for `m_flow_nominal` in this model.

**Comment by hcasperfu** [comment]
Thank you for spotting this!
This is actually a bit sticky.
`Movers.SpeedControlled_y` (and `_Nrpm`) requires that the user input the pressure curve so that it could assign a default `m_flow_nominal`, whilst `Movers.Preconfigured.SpeedControlled_y` works exactly the opposite way. For this reason, simply removing the assignment
`m_flow_nominal = max(per.pressure.V_flow)*rho_default;`
in speed-controlled models would break them.

The solution on top of my head would be "dumping" the `m_flow_nominal` assignment when the preconfigured model extends from its parent class. Redeclaring `m_flow_nominal` inside the extends-clause seems to do the trick.
```
  extends IBPSA.Fluid.Movers.SpeedControlled_y(
    ...
    redeclare parameter Modelica.Units.SI.MassFlowRate m_flow_nominal);
```
This also keeps the attributes (such as `min`) of `m_flow_nominal`.
With this change, Dymola would correctly throw the error message stating that "`m_flow_nominal` has no value", although the model can still pass the translation check with no problem.

**Comment by mwetter** [comment]
We may need to declare `m_flow_nominal` at a higher level, and then in the base class, use a protected value such as `_m_flow_nominal`. This way, one top-level class can provide a default but not the other.

**Comment by hcasperfu** [comment]
This path might be a bit painful.
`m_flow_nominal` is declared all the way down in `Fluid.Interfaces.PartialTwoPortInterface` and requires a value. Previously, its assignment at `Movers.SpeedControlled_y` was final. Therefore, previously the modification of `m_flow_nominal` was _forbidden_, and now it will become _required_.

**Comment by hcasperfu** [comment]
@mwetter 
Per our office discussion today regarding the legality of redeclaring without a `replaceable` keyword, I found this:
https://github.com/modelica/ModelicaSpecification/issues/1252
To sum up, it is legal when it does not change the type.

With this information, would you find the redeclaration to be an acceptable solution?

**Comment by mwetter** [comment]
I think in view of this restriction, redeclaring the parameter is fine if it was originally not declared as final, and if it works across the tools that we are testing (because MSL 3.5 states "An element declared as final shall not be modified, and thus not redeclared.")
