### ISSUE TITLE
Create tutorial for use at Modelica Conference

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#1785]
This issue is to create a tutorial for the Modelica Conference, including a development branch for https://github.com/ibpsa/modelica-ibpsa/pull/1783

**Comment by mwetter** [comment]
@jelgerjansen : thanks for the PR, which I moved to a development branch.

The development branch is `[issue1785_modelicaConfTutorial](https://github.com/ibpsa/modelica-ibpsa/tree/issue1785_modelicaConfTutorial)`

Can you please address the following.
- [ ] I suggest to rename `Fluid.Examples.WorkshopModelicaConference` to `Fluid.Examples.Tutorial.SimpleHouse` (as it will likely be used beyond the Modelica conference workshop).
- [ ] Create a regression test for each model that can be simulated. (Otherwise, we have no feedback if inadvertently something breaks, such as due to a change in the models that are being used.)
- [ ] Add a short description in the `info` section of the examples.
- [ ] Remove temporary LaTeX files (such as `.aux`, `.log`)
- [ ] Move LaTeX files from `IBPSA/Resources/Documentation/WorkshopModelicaConference` to `IBPSA/Resources/Documentation/Fluid/Examples/Tutorial/SimpleHouse` (reproducing the package structure)

I have not yet reviewed the pdf documentation.

**Comment by jelgerjansen** [comment]
Thank you for your comments @mwetter!
I think I've addressed all your remarks.

For the regression test I based myself on the script of `IBPSA.Fluid.Examples.SimpleHouse`.

The description I added are very short since the actual documentation can be found in the pdf itself. If desired, we could also move the information in the pdf to the Info section of the model itself?

Please let me know if there is still something to be changed.

**Comment by mwetter** [comment]
@jelgerjansen : Thanks for the changes. 

Running the unit tests should indeed work by following the steps at the above link that you provided. Is something not working? You can see the BuildingsPy version here:
https://github.com/ibpsa/modelica-ibpsa/blob/5766402ebddd558f745653a23856320975ebbc0a/.travis.yml#L23
 That commit is essentially the same as `v5.0.0` that was released last Friday.

If you could move the information from the pdf document to the info section, that would be fantastic. This way, all documentation is together, and online library documentation (either through the tool or on the web page such as https://build.openmodelica.org/Documentation/IBPSA.Fluid.Examples.html) will have all documentation accessible without having to post the pdf somewhere separate. -- This would also remove the issue that the pdf has the CC license, but IBPSA authorized developing the library under BSD, so we would need to figure out how to address that. (It is also easier for others to integrate the library if there is only one single license, so avoiding mix of licenses is IMHO important.)

One small item I found was that Figure 5 lists `walCap.T` but this is not displayed. I also made other small editorial changes in the `*.tex` file, please pull the latest version before making edits.

**Comment by jelgerjansen** [comment]
@mwetter I removed the pdf and added the exercises to the information section of the different models.
However, I left out the introduction of the pdf (e.g. mentioning where they can find OpenModelica), since I think we want the Tutorial to be used by different software?

Now I am able to run the unit tests, but they seem to take forever on my pc, so I didn't add the new reference results yet...
The main issue was that the directory of my Dymola installation was not yet included in the `PATH` variable. Maybe this can be added to the information sheet.
Furthermore, I noticed that `IBPSA/Resources/Python-Sources`, to which the `PYTHONPATH` variable should point, does not exist. I created this directory myself and the unit tests seem to run, but I don't know if you need to do this?

**Comment by mwetter** [comment]
@jelgerjansen : Thanks for the changes. They look good.  I added the reference results and also updated the instructions for how to run the unit tests. I removed the text `IBPSA/Resources/Python-Sources`; this is needed for the `Buildings` library which has python sources in that directory, but it is not needed for `IBPSA`.

As the tutorial also includes modeling of weather data, heat transfer and controls, in addition to fluid modeling, I think it would actually be better placed in `IBPSA.Examples.Tutorial`. This way it also fits in with `IDEAS.Examples.Tutorial` and `Buildings.Examples.Tutorial` (the other libraries don't have such packages). Please let me know if you agree and I can move it to that place. 

Through a separate issue I can then also move `Fluid.Examples.SimpleHouse` which I think should be moved too, but as this is a backward incompatible change, it typically takes longer to get through the approval process, and therefore I think we should do this via a separate issue.

**Comment by jelgerjansen** [comment]
@mwetter thank you for updating the reference results and the documentation for running the unit tests!

I agree with moving the SimpleHouse tutorial to `IBPSA.Examples.Tutorial`.

I furthermore agree with moving `IBPSA.Fluid.Examples.SimpleHouse`. It might also be good to update the info section, e.g. by including the differences between that model and the models in the tutorial. Do you want/need me to create this issue?
