### ISSUE TITLE
add valve and damper with linear relationship between flow and lift for given authority

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#271]
For valves and air dampers, the mass flow rate increases sharply at low lifts, in particular, but not only, if the authority is low. This causes a large control gain at low lifts, which in turn can cause instability in the feedback control that may require a compensation at the input signal of the valve. Such instabilities can significantly affect computing time.

This ticket is to implement either a simple valve and air damper model, or to add to the existing models a parameter that causes the mass flow rate to be a linear function of the opening signal for the given valve (or damper) authority.

**Comment by mwetter** [comment]
@dhblum : Can you please check https://github.com/iea-annex60/modelica-annex60/blob/master/Annex60/Fluid/Actuators/Valves/TwoWayPressureIndependent.mo as this may give the needed functionality of the damper or valve in which the flow rate is proportional to the control signal. See also https://github.com/iea-annex60/modelica-annex60/issues/156

**Comment by dhblum** [comment]
I pushed a new branch https://github.com/ibpsa/modelica/tree/issue271_linearDamper for development.  The damper model implements the formulation from TwoWayPressureIndependent valve, except for parameters relevant to dampers are used instead of valves.  Therefore, I suggest creating a new base class with this core implementation from which both the valve and damper models could extend.
