### ISSUE TITLE
Problem with the non-linearity of the new Media

### ISSUE THREAD

**Issue by damienpicard** [ibpsa/modelica-ibpsa#40]
I re-run the test where a simple hydraulic system (a pump, a boiler with on-off control, a heated pipe and so varying input) to compare IDEAS and IDEAS using annex 60 baseClasses (see issue #15 ).

After approximately 2*E+5 seconds, I get the error that Dymola cannot solve this non-linear problem. I don't have the problem if I run the previous Media implementation (ConstantPropertyLiquidWater, for example from commit  SHA: SHAc7a3e2d106d4f85b451ee9d414ca842827078501)

To illustrate the problem, I add in Annex60/IDEAS_a60 two save total, one with the current Media implementation (giving the problem), one with the previous implementation (running smoothly). This can be found at: https://github.com/damienpicard/modelica-annex60/tree/issue40_HydraulicTestBenchIDEAS

**Comment by thorade** [comment]
Ran into the same problem today on Windows, the fix is more or less identical.
On Linux, the command for creating symlinks is `ln -s realfile symlink`,
on Windows the command is `mklink symlink realfile`.

For some reason I had to create a symlink for the `.lib` file, not for the `.a` file.
The full command then reads:
`mklink "C:\Program Files (x86)\Dymola 2015 FD01\bin\lib\ModelicaStandardTables.lib" "C:\Program Files (x86)\Dymola 2015 FD01\Modelica\Library\Modelica 3.2.1\Resources\Library\win32\ModelicaStandardTables.lib"`

Also note I had to use `win32` even though I am using Dymola 64bit on a Windows 7 64bit.
Might be different for different setups (e.g. when using the flag `Advanced.CompileWith64` !?).
