### ISSUE TITLE
add borefield model

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#422]
This issue is to implement the borefield model of @damienpicard which is needed for `IDEAS` and `Buildings`. If interesting for other libraries, we can discuss to move it to the `master` when it is finished/cleaned up.

**Comment by damienpicard** [comment]
@mwetter I uploaded the code on the branch #issue422_borefield.

**Comment by damienpicard** [comment]
@mwetter I've added unit tests for all the examples except some examples on the uppermost level. Those take longer to initialize and to run and I'm not sure they should be added to the unit test suit. There are 2 examples with FIXME which do not compile:
```
Annex60.Fluid.HeatExchangers.GroundHeatExchangers.Borefield.BaseClasses.Aggregation.Examples.transientFrac
```
and
```
Annex60.Fluid.HeatExchangers.GroundHeatExchangers.Borefield.BaseClasses.BoreHoles.BaseClasses.Examples.SingleBoreHolesInSerie
```
 I'm not sure why, as I can use the models contained in these examples by other models without getting an error.

**Comment by SebastianRoc** [comment]
Hello mwetter,

I am working on a model for a thermal ground storage with freezing the included water with Modelica at the moment. That is why I am intersted in your model, because I search for an example in which thermal storage is solved in 3D-model.
Could you provide me the file of the model?
Thanks in advance.
Sebastian

**Comment by thorade** [comment]
@SebastianRoc the model and files are in the branch `issue422_borefield`.
https://github.com/ibpsa/modelica/tree/issue422_borefield
If you used git to clone the repository, you can just switch to that branch,
otherwise you can download that branch as a zip file:
https://github.com/ibpsa/modelica/archive/issue422_borefield.zip

**Comment by Mathadon** [comment]
Or if that does not work, you can have a look at the IDEAS (https://github.com/open-ideas/IDEAS) library, which also contains the model in `IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield.Examples`

**Comment by MassimoCimmino** [comment]
@mwetter :

@damienpicard and I are resuming the development of the geothermal model. Should the development still be done on this issue and its associated branch (`issue422_borefield`)?

The broad scope of the work to be done is to (1) restructure the IDEAS model, (2) add automatic evaluation of temperature response function at initialization, (3) add medium package for propylene glycol-water (and potentially other) mixtures, (4) add validation cases from experimental and field monitored data.

**Comment by mwetter** [comment]
Feel free to use a new branch if this is easier than adapting the current
development version.

**Comment by damienpicard** [comment]
Development of the borefield model will continue on the branch `issue422b_borefield`.
@MassimoCimmino can you push your branch directly on this branch? We then both have writing permission which might be more convenient to start putting the models together. We can still issue pull request from our branch to the ibpsa branch when necessary.

**Comment by MassimoCimmino** [comment]
@mwetter @damienpicard 
I do not have permission to push to `issue422b_borefield`.

**Comment by damienpicard** [comment]
@MassimoCimmino I can not give you the rights. @mwetter should do it.

FYI: I'm working on the re-factorization of the borefield model. I'll propose a new structure soon and I will indicate which parts of the model would include your work. I'm currently working on my fork of IDEAS on the package `GroundHeatExchanger.Borefield2` and `GroundHeatExchanger.Data`:
https://github.com/damienpicard/IDEAS/tree/issue422b_borefield/IDEAS/Fluid/HeatExchangers/GroundHeatExchangers

Once I'm ready with my proposition of the new structure, we could discuss it on Skype. As it is now a busy period and I'm then off for some holidays, give me 2-3 weeks still...

**Comment by mwetter** [comment]
@MassimoCimmino : you should now have received an invitation for write permission.

**Comment by MassimoCimmino** [comment]
Thank you @mwetter 

@damienpicard I pushed our branch to `IBPSA/issue422b_borefield`. The models for g-functions, load aggregation and propylene glycol are implemented. The functions for borehole thermal resistances are also in there. We are now working on completing the documentation and validation of our models.

Enjoy your holidays.

**Comment by damienpicard** [comment]
@MassimoCimmino I have uploaded my revised model.

We should discuss the following items this Friday:
- borFiedDat record: should we make it replaceable parameter or just a parameter?
- T_start:
	- Should we allow the user to initialize the model with a temperature gradient in the vertical direction. According to me not, because the analytical solution is not discretized in the vertical direction
	- in GroundTemperatureResponse, T_undisturbed should be a parameter rather.
- why do you have the parameter __forceGFunCalc__?
- not clear to me how you define the aggregation length (it should cover the whole simulation length)
- is everything working fine with the sha?
- it seems not possible to run a model with 2 borefields.
- we should check to parallel and serie 2UTub connection. Results do not seem to differ.
- we should include your BoreholeThermalResistances into my model.

**Comment by damienpicard** [comment]
Discussion with @MassimoCimmino 

- single U-tube flag in record could be automatically replaced --> or remove it.
- remove TWallAve
- validation of sandbox experiment should be done. Resistances need to be fitted to take into account the fine effect of the aluminium pipe
- we should include the influence of the ambiant temperature. This should be part of a different issue.
- add a model for the losses of the pipes running from the borefield to the building. At the beginning, no interaction with the borefield should be considered.
- move all parameters related to simulation to the borefield instead of in the record.
- check whether all parameters are included in the shaGFunction
- verify that sha is working properly (sha are rather short)
- Make a model with 2 borefields --> should use two seperated records

**Comment by damienpicard** [comment]
- add also coaxial borehole

**Comment by MassimoCimmino** [comment]
@damienpicard I have done some major restructuration/renaming of the models. I made sure all the examples/validation still run. The new structure is the result of merging the directories from your models and mine. I will now move on to the modifications we discussed on Friday in the next few days.

**Comment by damienpicard** [comment]
Following items have been done:
- remote flag single U-Tube. I use now a type. Type is necessary for double U-Tube to specify whether they are configured in parallel or serie. For consistancy, I added a type singleUTub as well.
- TWallAve is now removed
- validation of sandbox experiment is added. @MassimoCimmino : Rb should be tuned due to Al pipe

We should also be aware that if the ground model is modified by not the record, previous precomputed responses with still be used, useless they are deleted. This might be problematic for unaware users (who either made some changes or who pulled a newer version but use the same simulation repository). Maybe the default value of forceSha should be on `True` and documentation should clarify it uses?

**Comment by damienpicard** [comment]
@MassimoCimmino each time I close Dymola, Dymola asked me if I want to save the bessel functions and the exponent function. There must be sth wrong with the line ending.

**Comment by MassimoCimmino** [comment]
@damienpicard I fixed the issue with the bessel functions. I also agree on your point concerning the sha. 

Kind of related, we have been working on an implementation of the SHA1 algorithm to produce constant sized alphanumeric hashes and replace the current implementation. Strangely, when calling the sha function (the new one or the old one) the solver decides to only keep 499 characters (max) to send to the c-function, instead of the full string. This becomes an issue with larger fields since the coordinates of all of the boreholes are included into the string to be hashed. Any insight on this?

I will make a list of what remains to be done on the models and post it here in the coming days for discussion/comments.

**Comment by damienpicard** [comment]
@Mathadon do you have any idea about Massimo's question? (about the sha)

**Comment by MassimoCimmino** [comment]
@damienpicard @Mathadon About the SHA, this was actually a false alarm. The strings are only truncated for printing purposes. They are communicated correctly to the c-function. We were only confused by some cryptic warning message in Dymola. Sorry about that.

**Comment by thorade** [comment]
If it is just the printing, and the error message was "Room to allocate string" then you could try to fix that:
go to $Dymola$/source/matrixop.h and increase the size of simplestring by e.g. a factor of 10.

**Comment by MassimoCimmino** [comment]
@damienpicard 

A few questions:
- Should `Types.BoreHoleConfiguration` be changed to `Types.PipeConfiguration` and contain only `Series` and `Parallel`? `SingleUTube`seems unnecessary if there are already two different models for Borefields.
- Is it really necessary to have the discretization parameters `nVer`and `nHor` (this one I guess is not even used) inside the records? They are more related to the simulation than to the borefield configuration.
- Same as previous, escept for nominal/starting conditions: `m_flow_nominal`, `dp_nominal`, `p_constant`.

**Comment by damienpicard** [comment]
@MassimoCimmino 

- as  the boreholeConfiguration is defined in the record conDat which is both used for single and double U-Tube, it seems more convenient to me to also use a singleUTube type. Otherwise, in case of singleUTube pipe you get a parameter in conDat which is unused and maybe confusing.
- we can rename it with `PipeConfiguration`
- we can move nVer, m_flow_nominal,  and dp_nominal to the borefield model and drop nVer and p_constant 
- I'm not sure anymore for Rb. This should be checked.

**Comment by damienpicard** [comment]
@MassimoCimmino why do you need the factor `0.5` for ILS and `2 pi` for CHS in https://github.com/ibpsa/modelica-ibpsa/blob/issue422b_borefield/IBPSA/Fluid/HeatExchangers/GroundHeatExchangers/GroundHeatTransfer/ThermalResponseFactors/gFunction.mo (short term part) and why aren't they included in the inifiteLineSource and cylindricalHeatSource function?

**Comment by MassimoCimmino** [comment]
@damienpicard The conventions for non-dimensionalisation of the analytical models are different. I implemented each based on their classical formulation. The factors come from the definition of the g-function, which needs the temperature variation to be dT = q/(2.pi.k) * g(t).

The definition for each of the FLS, ILS and CHS are in the documentation (repeated here). The factors make all solutions have the same form as the g-function definition, above.

FLS:
![finitelinesource_01](https://user-images.githubusercontent.com/23085996/40991428-c5c3805a-68c1-11e8-8dc0-fbc906708544.png)
ILS:
![infinitelinesource_01](https://user-images.githubusercontent.com/23085996/40991362-8f38c680-68c1-11e8-9b89-fb44ddc6f4c2.png)
CHS:
![cylindricalheatsource_01](https://user-images.githubusercontent.com/23085996/40991446-cd9e787a-68c1-11e8-8263-557e67ce43e5.png)

**Comment by damienpicard** [comment]
@MassimoCimmino thank you for the clarification.

Something else we should be awared of: if we use a coarse tLoaAgg (e.g. 3600 s), the borehole wall temperature will not show a very physical value. Example: `IBPSA.Fluid.HeatExchangers.GroundHeatExchangers.Examples.Borefields` at tLoaAgg=3600 s looks like this:
![image](https://user-images.githubusercontent.com/2987659/40997229-408f3ac6-6904-11e8-96f5-dd1712f8e584.png)

**Comment by MassimoCimmino** [comment]
@damienpicard Your comment made me find some small related mistake I made while moving the models to this branch. The aggregation used the instantaneous heat flow rather than the average over an aggregation step. I pushed a fix to [7621d70](https://github.com/ibpsa/modelica-ibpsa/commit/7621d707c6a40bc630c5d54c706f11b3a36e7278).

This does not entirely fix the issue you pointed out. The case you are looking at has a fast response time. Right now, I would advise using a fraction of the fluid travel time for `tLoaAgg`. I have set it to 300s in the validation case. We should certainly work out some recommandation for the value.

**Comment by damienpicard** [comment]
@MassimoCimmino do we need to prepare anything for the call of 14/06?

**Comment by MassimoCimmino** [comment]
@damienpicard I presented the status of the development on the last call and we have only implemented minor changes since then, so I guess not.

**Comment by MassimoCimmino** [comment]
@damienpicard I finished the implementation of the thermal resistances functions into your resistance-capacitance models. I believe all that is left now is verification/cleaning, validation/examples and documentation.

Regarding verification, in your examples `IBPSA.Fluid.HeatExchangers.GroundHeatExchangers.Boreholes.BaseClasses.Examples.InternalHEXOneUTube` and `IBPSA.Fluid.HeatExchangers.GroundHeatExchangers.Boreholes.BaseClasses.Examples.InternalHEXTwoUTube`, where does R_ref come from ?

**Comment by Mathadon** [comment]
@MassimoCimmino if at all possible we would like to include the new borefield model in our next IDEAS release, by the end of July. Is it feasible to finish this pull request by then?

**Comment by damienpicard** [comment]
@MassimoCimmino `Rb_ref ` was computed using EED if I remember correctly. That been said, I'm not sure I did not change the record during the restructuring, so I should recompute the value to be sure.

Or, as you probably have a validation model for your resistances calculation, we can use your record and your reference value?

**Comment by MassimoCimmino** [comment]
@Mathadon It is possible, but might prove difficult given I will be out of the office for the first week of July. If everything goes extremely well, the PR could be ready by mid-July but I expect the review to take some time given the extent of the model (there is already 174 changed files...).

@damienpicard I have some test cases in preparation for the thermal resistances return by the multipole solution for non-symmetric pipe configurations. I will try and find one for a symmetric case.

**Comment by mwetter** [comment]
Maybe there are packages that can be reviewed earlier? I will be out of the office after July 20. Another option would be move it to IBPSA.Experimental for a less tested release, or make a minor release of IDEAS once the model is reviewed and included in IBPSA.Fluid.

**Comment by MassimoCimmino** [comment]
We could have a first review for the packages related to ground heat transfer. This would include the new models/functions in:

- IBPSA.Fluid.HeatExchangers.GroundHeatExchangers.GroundHeatTransfer
- IBPSA.Fluid.HeatExchangers.GroundHeatExchangers.Data
- IBPSA.Utilities.Cryptographics
- IBPSA.Utilities.Math

I should be feasible to have these packages ready sometime during the next week.

**Comment by mwetter** [comment]
@damienpicard @MassimoCimmino @AlexLaferriere  This model is now on the master. Thank you very much for your substantial contribution and all the time you put into it.
