### ISSUE TITLE
Merge new pipe model

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#805]
This issue is to merge the pipe model from https://github.com/bramvdh91/modelica-ibpsa/issues/18

**Comment by bramvdh91** [comment]
This should solve the issue with files that should not be changed. Will add some simpler examples with just a temperature step or a mass flow reversal.

**Comment by mwetter** [comment]
@bramvdh91 : I got started on revising the pipe model but have a few questions:
1. The plot on https://github.com/ibpsa/modelica-ibpsa/network shows that there are 3 different branches being worked on. Which one is the version I should review and revise, and eventually merge to the master?
1. I kept revising the branch `issue805_pipe` today, but noticed that there is a pipe in the `Experimental.Pipe` package, and also in the directory `IBPSA/Fluid/PlugFlowPipess`. The latter does not show up in Dymola as it has no `package.mo` file, but it was added to git on June 30. `Experimental.Pipe` seems to be a very rough implementation. Which one are the ones that should be revised and merged to the master?

**Comment by bramvdh91** [comment]
@mwetter : Thanks!
ad 1.: Branch `issue805_pipe` is the one where I moved all models that are described or referred to in the ECM paper. Regarding my fork: 

- In `issue264_pipe` I have made some additional changes, I'll check which ones should be forwarded to #805. 
- In `pipe_issue76_static` @marcusfuchs has implemented a static heat loss implementation which we are comparing to the dynamic model together with Gerald Schweiger and Keith O'Donovan. 
- In `issue_zeroFlowLosses` I have implemented a calculation of the actual heat losses during flow standstill, based on the average temperature in the pipe. This could be interesting to include later on, but validation would be needed. 

ad 2.: `IBPSA/Fluid/PlugFlowPipess` is indeed a duplicate, I have deleted it accordingly. The pipes in `Experimental.Pipe` are the double pipe implementations which are not validated (because of lacking measurements with supply and return temperature). `Experimental.Pipe.Template` provides an implementation where the user can choose a diameter and construction type from catalog data (via a drop-down menu), but I did not think this should be merged into the master yet. We had a discussion whether the final model should include catalog data or not, but there we concluded it would be best to have the basic model as in `Fluid.PlugFlowPipes` and provide a wrapper class with catalog data.

**Comment by bramvdh91** [comment]
I have noticed now that some simulate and plot scripts have been misplaced, I'm adding those back before tomorrow.

**Comment by mwetter** [comment]
@bramvdh91 If `Experimental.Pipe.Template` or `Experimental.Pipe` should not yet be merged to the master, can you please put them on a separate branch, and clean up `issue805_pipe` so that `issue805_pipe` only contains what needs to be merged to the `master`. I can then review `issue805_pipe` and merge the whole branch `issue805_pipe`, but I cannot do a partial merge of `issue805_pipe`. I will be out until mid next week, so no rush.

**Comment by bramvdh91** [comment]
Okay @mwetter, I'll do that. Is there anything I can already pay attention to regarding cleaning up the models that will be merged as far as you have reviewed them?

**Comment by mwetter** [comment]
@bramvdh91 
As there were various versions and I didn't see what is ready to merge, I didn't spend much time in revising the models. I suggest you start with making sure to follow
https://github.com/ibpsa/modelica-ibpsa/wiki/Style-Guide
and run the unit tests:
https://github.com/ibpsa/modelica-ibpsa/wiki/Unit-Tests

This will then make revising much simpler and faster.

**Comment by marcusfuchs** [comment]
This is now merged.

**Comment by Mathadon** [comment]
milestone, check!

**Comment by marcusfuchs** [comment]
Yeah, I'm celebrating!

**Comment by mwetter** [comment]
I'm glad its merged! Thanks for your work!
