### ISSUE TITLE
set up examples so that they have flow rates above m_flow_turbulent

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#825]
The example `ResistanceVolumeFlowReversal` has flow rates through the parallel resistances that are well below `m_flow_turbulent`. Hence, depending on whether a tool solves m_flow = f(dp) or dp=g(m_flow), mass flow rates in the parallel branches can differ.

This issue is to fix the model so that the flow rate is at or above `m_flow_turbulent`, in which case m_flow = f(dp) and dp=g(m_flow) gives identical results. This is needed as different tools may solve the equation differently, and hence the verification would fail. For example, Dymola 2018FD01 beta2 fails the tests because of this.

A similar problem may apply to `Simplified1`, which has these differences, produced with dymola 2018FD01 beta2:
![image](https://user-images.githubusercontent.com/1329080/30720225-78c2ccda-9edb-11e7-9908-954254b670d8.png)

@Mathadon : Can you please change `Simplified1` so that its flow rates are above `m_flow_turbulent`. I changed this for `ResistanceVolumeFlowReversal`

**Comment by Mathadon** [comment]
@mwetter I changed the simulation duration of the example in 112339460ed2d17bf9681628960d5613c4964013, such that it evolves from its initial conditions into a simulation region with higher flow rates.

However, I expect the verification will still fail since the model will still operate in the turbulent region. The tool implementation differences will/should therefore still be triggered. The proper way of solving this is to find an implementation for the flow functions for `from_dp=true` and `from_dp=false` that is consistent. Currently the two implementations are not each others inverse, which is the root of the problem.

**Comment by Mathadon** [comment]
@mwetter this is ready as far as I am concerned!

**Comment by mwetter** [comment]
@Mathadon : Did you check the simulations? `Simplified1.mos` does not converge. See https://github.com/ibpsa/modelica-ibpsa/pull/854

**Comment by Mathadon** [comment]
@mwetter : I did, since I was able to update its reference result in 1123394 . I recall that this was the reason for limiting the simulation time for this specific model: it does not converge without the simplifications. I suppose that it depends a bit on the exact configuration/version of dymola whether or not it converges..
Would it make sense to add a flag in buildingspy that a model does not need to converge? E.g. in this case we were originally mostly interested in statistics.

**Comment by mwetter** [comment]
Maybe we should reduce the stop time then for this example.

Non-convergent models would cause issues if we were to accept them in BuildingsPy, as then, verification tests with OpenModelica and JModelica would flag an error because they likely would fail to simulate the model as well, but expect it to complete without error.

**Comment by Mathadon** [comment]
@mwetter then this issue is not solved? Or we could initialise the normalised pump speed to 1 such that the model starts with a large flow rate..? If that does not trigger the bug of course.
