### ISSUE TITLE
updates to MediumColumn

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#877]
`IBPSA.Airflow.Multizone.MediumColumn` does not implement `allowFlowReversal` for the computation of `h_outflow`, etc. 

Furthermore, this model computes the density from the absolute pressure. The pressure can depend on the mass flow rate and thus on the density, which generates an algebraic loop. The impact of the absolute pressure on air/water density is negligible such that we could add an option to simplify the density computation by using a constant pressure for the evaluation of density.

**Comment by mwetter** [comment]
The intentional use of `MediumColumn` is to compute the pressure difference due to differences in density, for example for modeling stack effect in buildings. 

I think `allowFlowReversal` would be confusing and probably error-prone. Consider two rooms, one on the 1st floor, and one on the second floor, and suppose the pressure is understood to be at the average of the respective room's height (as in `Examples.ReverseBuoyancy`). Then, you want to describe with what temperature the medium is computed, and not whether you have reverse flow. Also, flow is likely to reverse in models where buoyancy is a driving force.

Using only `rho=f(T)` rather than `rho=f(T, p)` as long as all instances of `MediumColumn` are configured consistently. Otherwise you may get flow even if all medium pressures and temperatures are equal, e.g., a perpetuum mobile. Do you see a measurable performance gain for this?

**Comment by Mathadon** [comment]
@mwetter I can see why `allowFlowReversal=false` can be a bad idea since the flow can indeed reverse due to inverse temperature gradients, but then the parameter should be removed? It currently exists and only modifies the `min`,`max` attributes.

I would then propose to use `rho=f(T)` by default instead of `rho=f(T,p)` since pressure differences are typically in the order of 100 Pa, which is negligible compared to the absolute pressure of 100 kPa. I'm wondering whether the existing implementation in fact can't also introduce a perpetuum mobile.. Since the model is asymmetric: it takes the absolute pressure of one of the two ports to compute the density.
Anyway, I saw a case where this pressure-dependency leads to an algebraic loop in 1 iteration variable. Whether this is measurable depends on the case of course. I'm rather safe than sorry when it comes to avoiding algebraic loops.

**Comment by mwetter** [comment]
@Mathadon : Yes, this parameter should be removed (which will be a backward incompatible change). It is also used in `PowerLawResistance` which is used by the orifice model. It looks like it got in there when the base classes were changed. In my view, we should not allow setting `allowFlowReversal = false` in this package.

Using rho=f(T) by default instead of rho=f(T,p) should be fine.

The existing implementation cannot cause a perpetuum mobile _if_ all heights are entered consistently and the parameter that picks the state to compute the density is set to the correct port.

**Comment by Mathadon** [comment]
@mwetter that's a large if ;)

I will remove the parameter.
