### ISSUE TITLE
Variable density in pump

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#878]
Similar to #877, the pump models use pressure-dependent functions to compute the fluid density, which could introduce additional algebraic loops. I think there used to be an option to disable this, which seems to have been removed? What was the cause for this?

**Comment by mwetter** [comment]
Could it introduce algebraic loops, or does it introduce algebraic loops?
A problem of using a constant density would be to make sure that users set the right density, e.g., assign `Medium.p_default`. Otherwise, you get quite a difference in fan performance if buildings are in high elevations.

**Comment by Mathadon** [comment]
Would it help if we set `rho_default` using an initial equation using the actual pressure? Otherwise we can at least provide the option to do so.

I'll check if I can be more specific regarding the algebraic loops.

**Comment by mwetter** [comment]
Let's first check whether using the actual pressure really makes a notable
difference in performance.

The issue with setting the pressure from the initial pressure is that
a) it may make the initialization problem harder?, and
b) if you have two simulations of the same model, but one starts when the
fan is on, and the other when the fan is off, then the simulation results
during the time stepping will be different due to the difference in
density. Hence, the initial control signal will determine the performance
of the model during simulation, which is physically wrong.

**Comment by Mathadon** [comment]
I can't think of any typical use case where the variable density would lead to more iteration variables in algebraic loops. However, it does lead to more equations in the algebraic loops. The performance penalty due to this should however be limited if tearing is implemented efficiently (i.e. if it does not lead to more iteration variables).

Therefore I propose to close this issue.
