### ISSUE TITLE
csv writer

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#924]
I think it would be useful to have a simple csv writer model that generates a csv file by sampling some inputs. This would result in a file type that is easier to post-process than the usual .mat files. I'm making this model so might as well add it to the library?

**Comment by Mathadon** [comment]
@dhblum this can be of interest for BOPTEST too.

**Comment by mwetter** [comment]
@Mathadon : Have you considered https://github.com/lbl-srg/modelica-buildings/pull/1152, e.g., the files in `Buildings.Utilities.Plotter`. What would be interesting there for the CSV writer is how to specify when to sample, and where to write the results, e.g., have different "CSVWriter" spread out through your hierarchical model, but they all write to the same file.  Changing from the current html output to csv output should be quite easy, and I could port it to `IBPSA` if there is interest.

**Comment by Mathadon** [comment]
@mwetter thanks for the suggestion. I checked the code quickly (was not aware of this functionality) and it looks a bit overkill. I.e. I just made an implementation that uses much less code (here https://github.com/ibpsa/modelica-ibpsa/commit/e47eec35dd7650d96aebe46b32707d0b03ce3459) so that may save you the time to change your code. Do you see advantages of your implementation compared to mine?

Integrating multiple csv writers should be possible but it could become involved and the file column orders may change based on how the tool processes the code, which may lead to problems depending on the use case.

If you like my implementation: how should we unit-test this?

**Comment by mwetter** [comment]
@Mathadon : So you don't like overkill?  The main advantage of my implementation is that you can put the plotters anywhere in the file, and plot data from different models to the same file, a feature we need to quickly add plotters for control verification. This is why the implementation in C got more complex. If desired, you could do the same for your CSV output. The order of columns would be consistent across tools if you give as default column name the instance name of the model that instantiates the plotter appended by a number. Using such a name would anyway be better IMHO because this would tell you in the CSV file by default where the signal comes from.

Although, my implementation allows to disable plotting for example if I am only interested in plotting control signals when the fan is on for at least 5 minutes (which may not be that important for CSV output).

There are a few issues/suggestions with your implementation:
- [ ] Rename `sampleTime` with `samplePeriod` as the MSL (and IBPSA) already uses `samplePeriod`.
- [ ] If each plotter writes to its own file, then there is no need to use C functions. You can use directly functions from `Modelica.Utilities.{Files,Streams}`.
- [ ] For `simulateModel("IBPSA.Utilities.IO.Examples.CsvWriter", startTime=-0.1, stopTime=10, method="dassl", resultFile="CsvWriter");` you get non-equidistant time stamps. I don't think you want this behavior. See `Buildings.Controls.OBC.CDL.Discrete.Sampler` for how to use `samplePeriod` without having to specify the start time.
- [ ] Rename `nIn` to `nin` (to be consistent with `Modelica.Blocks.Interfaces.MISO`).
- [ ] Use `RealVectorInput` so that the user does not have to specify `nin`.
- [ ] Rename `IBPSA.Utilities.IO.CsvWriter` to `IBPSA.Utilities.IO.Reports.CSVWriter` (e.g., make a package for Reports, and I suggest to capitalize CSV). Using `IO.Reports` would fit with the existing package structure of `Buildings.Utilities.IO.Reports`; or alternatively you could use `Files` but then I would have to change the Buildings library structure at some point.
- [ ] For the default value of `fileName`, why not using `getInstanceName() + ".csv"`. Otherwise, if a user drags in multiple plotters, they overwrite each other. Better would be to make sure on the C level that each `fileName` is only used once.

**Comment by Mathadon** [comment]
I checked `Modelica.Utilities.{Files,Streams}` but could not find a function for creating an empty file. 
I'm not sure how using `RealVectorInput` does not require the user to define `nin`? So I used the vector, but did not remove `nin`.
I tried to implement some functionality that check whether multiple models are writing to the same file,  by checking whether the file exists and is empty before creating it. Somehow the code does not behave as intended. I tried both a Modelica and C implementation and the issue may be caused by the way that Dymola translates the code. Possible some code is compiled and executed during translation instead of during initialization.

@mwetter can we do without this functionality?

**Comment by mwetter** [comment]
@Mathadon : I added `annotation(Evaluate=true, Dialog(connectorSizing=true))` to `nin` to enable automatic connector sizing, and renamed `C-sources` to `C-Sources`.

Your implementation of `createFile` did not work because there is no guarantee that the `initial algorithm` section is only executed once. Code that need to be executed exactly once must be in a `class` that extends `ExternalObject`.

I see if I can fix this in the next days.

**Comment by mwetter** [comment]
@Mathadon : I added the `ExternalObject`. Now, if two CSV writers write to the same file, the simulation stops with an error.

I also did some other modifications.

Can you please add a regression test, and also consider moving some parameter such as the delimiter to the `Advanced` tab.
