### ISSUE TITLE
indicate license in github

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#960]
Github has the option to indicate the license on the website, see e.g. https://github.com/casadi/casadi where LGPL-3.0 is clearly indicated. Can/should we add this for IBPSA too?

**Comment by thorade** [comment]
That is displayed automatically by GitHub, if the text in LICENSE.md matches exactly one of the known licenses.
https://blog.github.com/2016-09-21-license-now-displayed-on-repository-overview/
The IBPSA license is in a different place, it is in HTML, and it has some sentences added for contributors.

**Comment by mwetter** [comment]
Because of the added paragraph that makes it easy and clear how to accept contributions, it is not plain BSD license and hence I prefer not to mark it on github as BSD. Converting the license to .md would be fine, but there need to be a license file in the IBPSA directory as tools would include the library with the IBPSA directory as the top-level directory.

**Comment by Mathadon** [comment]
Ok, this can be closed then as far as I'm concerned.
