### ISSUE TITLE
extend assert error messages

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#962]
Sometimes asserts are triggered but since Dymola does not necessarily output results exactly at that timestamp, these asserts can be tough to debug when the occur in exceptional circumstances. I then often have to add additional print statements in the assert message itself, like the two last lines below for `IDEAS.Fluid.Interfaces.StaticTwoPortConservationEquation`.

```
    assert(noEvent( abs(Q_flow) < 200*cp_default*max(m_flow_small/1E3, abs(m_flow))),
   "In " + getInstanceName() + ": Energy may not be conserved for small mass flow rates. 
   The implementation may require prescribedHeatFlowRate = false. 
   The heat flow rate equals " + String(Q_flow) +
   " W and the mass flow rate equals " + String(m_flow) + " kg/s")
```

Are these things that I can systematically start making pull requests for, or does this make the error messages too 'heavy'?

**Comment by mwetter** [comment]
You could check on a large model, or a model with a few hundred of these StaticTwoPortConservationEquation instances, what the compile time overhead is.

Looking at this message is also on our todo list, see https://github.com/lbl-srg/modelica-buildings/issues/1179
I think removing the `noEvent` helps, but we would need to check if we get many more events due to this removal.

**Comment by Mathadon** [comment]
I’m not sure what the overhead would be for simply extending an existing assert? By ‘heavy’, I mostly mean that the messages can be come a bit long for the user to deal with.

**Comment by mwetter** [comment]
Longer messages are good if they provide better diagnostics for the user.
